---

- name: Include set_facts
  ansible.builtin.import_tasks: set_facts.yml

- name: Include upgrade
  ansible.builtin.import_tasks: upgrade.yml
  when: >
        phpipam_upgrade or
        phpipam_install_from_git

- name: Include debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include redhat
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include cron
  ansible.builtin.import_tasks: cron.yml
  tags:
    - config_cron

- name: Include config_apache2
  ansible.builtin.import_tasks: config_apache2.yml
  tags:
    - config_apache2
  when: >
        phpipam_prettify_links is defined and
        phpipam_prettify_links

- name: Include config_phpipam
  ansible.builtin.import_tasks: config_phpipam.yml
  tags:
    - config_phpipam

- name: Include backups
  ansible.builtin.import_tasks: backups.yml
  tags:
    - phpipam_db_backups
  when: >
        phpipam_enable_db_backups is defined and
        phpipam_enable_db_backups
