---
- name: Redhat | installing pre-req packages
  ansible.builtin.yum:
    name: "{{ phpipam_redhat_packages }}"
    state: present
  become: true
  register: result
  until: result is succeeded
  when: ansible_distribution != "Fedora"

- name: Redhat | setting php timezone
  ansible.builtin.lineinfile:
    dest: /etc/php.ini
    line: "date.timezone = {{ phpipam_timezone }}"
  become: true
  notify: restart httpd
