---
- name: Upgrade | checking {{ phpipam_install_dir }}
  ansible.builtin.stat:
    path: "{{ phpipam_install_dir }}"
  register: phpipam_install_dir_check

- name: Upgrade | moving directory {{ phpipam_install_dir }}
  ansible.builtin.command: "mv {{ phpipam_install_dir }} {{ phpipam_install_dir }}.{{ date }}"
  become: true
  changed_when: phpipam_install_dir_check.stat.isdir is defined and phpipam_install_dir_check.stat.isdir
