---
- name: Upgrade | checking {{ phpipam_install_dir }}
  ansible.builtin.stat:
    path: "{{ phpipam_install_dir }}"
  register: phpipam_install_dir_check

- name: Upgrade | moving directory phpipam_install_dir {{ phpipam_install_dir }}.{{ date }}
  ansible.builtin.command: "mv {{ phpipam_install_dir }} {{ phpipam_install_dir }}.{{ date }}"
  become: true
  when: phpipam_install_dir_check.stat.exists
