---
# handlers file for ansible-phpipam
- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
  become: true

- name: Restart_php5-fpm
  ansible.builtin.service:
    name: php5-fpm
    state: restarted
  become: true
