---
# handlers file for ansible-phpipam
- name: Restart apache2
  service:
    name: apache2
    state: restarted
  become: true

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  become: true

- name: Restart_php5-fpm
  service:
    name: php5-fpm
    state: restarted
  become: true
