---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu2004
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
