---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Verify apache
    ansible.builtin.uri:
      url: http://localhost/
      status_code: 200
